import type { Vehicle } from "../types";

const now = new Date().toISOString();

export const dummyVehicles: Vehicle[] = [
  {
    _id: "v1",
    make: "Chevrolet",
    model: "Corvette",
    category: "Coupe",
    price: 68300,
    quantity: 3,
    year: 2024,
    vin: "1G1YB2D45P5100001",
    description: "Mid-engine sports coupe with striking performance.",
    imageUrl: "/cars/chevy-corvette.png",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "v2",
    make: "Ford",
    model: "F-150",
    category: "Truck",
    price: 45200,
    quantity: 6,
    year: 2024,
    vin: "1FTFW1E84PFA00002",
    description: "Full-size pickup with best-in-class towing capacity.",
    imageUrl: "/cars/ford-f150.png",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "v3",
    make: "Honda",
    model: "Civic",
    category: "Sedan",
    price: 24500,
    quantity: 14,
    year: 2024,
    vin: "2HGFE2F50PH000003",
    description: "Compact sedan known for reliability and efficiency.",
    imageUrl: "/cars/honda-civic.png",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "v4",
    make: "Jeep",
    model: "Wrangler",
    category: "SUV",
    price: 41800,
    quantity: 7,
    year: 2024,
    vin: "1C4HJXDG0PW000004",
    description: "Off-road capable SUV with removable doors and roof.",
    imageUrl: "/cars/jeep-wrangler.png",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "v5",
    make: "Mercedes-Benz",
    model: "C-Class",
    category: "Sedan",
    price: 47500,
    quantity: 4,
    year: 2024,
    vin: "W1KWF8DB0PR000005",
    description: "Luxury sedan with a refined interior and smooth ride.",
    imageUrl: "/cars/mercedes-cclass.png",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "v6",
    make: "Porsche",
    model: "911",
    category: "Coupe",
    price: 118500,
    quantity: 2,
    year: 2024,
    vin: "WP0AB2A99PS000006",
    description: "Iconic sports car with legendary handling.",
    imageUrl: "/cars/porsche-911.png",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "v7",
    make: "Tesla",
    model: "Model 3",
    category: "Sedan",
    price: 42990,
    quantity: 9,
    year: 2024,
    vin: "5YJ3E1EA0PF000007",
    description: "Electric sedan with long range and Autopilot.",
    imageUrl: "/cars/tesla-model3.png",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "v8",
    make: "Toyota",
    model: "Camry",
    category: "Sedan",
    price: 28500,
    quantity: 12,
    year: 2024,
    vin: "4T1G11AK0PU000008",
    description: "Reliable midsize sedan with excellent fuel economy.",
    imageUrl: "/cars/toyota-camry.png",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "v9",
    make: "Toyota",
    model: "RAV4",
    category: "SUV",
    price: 30800,
    quantity: 11,
    year: 2024,
    vin: "2T3W1RFV0PW000009",
    description: "Compact SUV with standard AWD and generous cargo space.",
    imageUrl: "/cars/toyota-rav4.png",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "v10",
    make: "Toyota",
    model: "Camry Hybrid",
    category: "Sedan",
    price: 31200,
    quantity: 5,
    year: 2024,
    vin: "4T1G11AK0PU000010",
    description: "Hybrid variant of the Camry with improved fuel economy.",
    imageUrl: "/cars/toyota-camry.png",
    createdAt: now,
    updatedAt: now,
  },
];